name: .NET

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Restore dependencies
      run: dotnet restore
      working-directory: CSISD-Tolling-System
    - name: Build
      run: dotnet build --no-restore
      working-directory: CSISD-Tolling-System
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: CSISD-Tolling-System
